export type Entry = {
  index: number;
  name: string;
  frameSrc: string;
  contestantSrc: string;
  iconSrc: string;
  spIconSrc: string;
  spBannerSrc: string;
  spKirinukiSrc: string;
  spNameSrc: string;
  spInfoSrc: string;
  iconAlt: string;
  description: string;
  twitterLink: string;
  youtubeLink: string;
  niconicoLink: string;
  isPublished: boolean;
};

const entries: Entry[] = [
  {
    index: 1,
    name: '阿保草',
    frameSrc: '/Entry/Frame/21_Entry_Frame_01.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_01.png',
    iconSrc: '/Modal/icon/22_Modal_icon_01.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_01.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_01.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_01.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_01.png',
    spInfoSrc: '',
    iconAlt: '',
    description: '',
    twitterLink: '',
    youtubeLink: '',
    niconicoLink: '',
    isPublished: true
  },
  {
    index: 2,
    name: 'アンデス',
    frameSrc: '/Entry/Frame/21_Entry_Frame_02.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_02.png',
    iconSrc: '/Modal/icon/22_Modal_icon_02.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_02.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_02.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_02.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_02.png',
    spInfoSrc: '',
    iconAlt: '',
    description: '',
    twitterLink: '',
    youtubeLink: '',
    niconicoLink: '',
    isPublished: true
  },
  {
    index: 3,
    name: 'イダルゴ',
    frameSrc: '/Entry/Frame/21_Entry_Frame_03.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_03.png',
    iconSrc: '/Modal/icon/22_Modal_icon_03.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_03.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_03.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_03.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_03.png',
    spInfoSrc: '',
    iconAlt: '',
    description: '',
    twitterLink: '',
    youtubeLink: '',
    niconicoLink: '',
    isPublished: true
  },
  {
    index: 4,
    name: '芋タルト',
    frameSrc: '/Entry/Frame/21_Entry_Frame_04.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_04.png',
    iconSrc: '/Modal/icon/22_Modal_icon_04.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_04.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_04.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_04.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_04.png',
    spInfoSrc: '',
    iconAlt: '',
    description: '',
    twitterLink: '',
    youtubeLink: '',
    niconicoLink: '',
    isPublished: true
  },
  {
    index: 5,
    name: 'エロう丸イクイクイクイクイクイク',
    frameSrc: '/Entry/Frame/21_Entry_Frame_05.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_05.png',
    iconSrc: '/Modal/icon/22_Modal_icon_05.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_05.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_05.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_05.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_05.png',
    spInfoSrc: '',
    iconAlt: '',
    description: '',
    twitterLink: '',
    youtubeLink: '',
    niconicoLink: '',
    isPublished: true
  },
  {
    index: 6,
    name: 'KAISATSU',
    frameSrc: '/Entry/Frame/21_Entry_Frame_06.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_06.png',
    iconSrc: '/Modal/icon/22_Modal_icon_06.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_06.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_06.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_06.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_06.png',
    spInfoSrc: '',
    iconAlt: '',
    description: '',
    twitterLink: '',
    youtubeLink: '',
    niconicoLink: '',
    isPublished: true
  },
  {
    index: 7,
    name: 'カスk°',
    frameSrc: '/Entry/Frame/21_Entry_Frame_07.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_07.png',
    iconSrc: '/Modal/icon/22_Modal_icon_07.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_07.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_07.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_07.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_07.png',
    spInfoSrc: '',
    iconAlt: '',
    description: '',
    twitterLink: '',
    youtubeLink: '',
    niconicoLink: '',
    isPublished: true
  },
  {
    index: 8,
    name: '神酒',
    frameSrc: '/Entry/Frame/21_Entry_Frame_08.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_08.png',
    iconSrc: '/Modal/icon/22_Modal_icon_08.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_08.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_08.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_08.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_08.png',
    spInfoSrc: '',
    iconAlt: '',
    description: '',
    twitterLink: '',
    youtubeLink: '',
    niconicoLink: '',
    isPublished: true
  },
  {
    index: 9,
    name: '♪くらっち♪',
    frameSrc: '/Entry/Frame/21_Entry_Frame_09.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_09.png',
    iconSrc: '/Modal/icon/22_Modal_icon_09.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_09.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_09.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_09.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_09.png',
    spInfoSrc: '',
    iconAlt: '',
    description: '',
    twitterLink: '',
    youtubeLink: '',
    niconicoLink: '',
    isPublished: true
  },
  {
    index: 10,
    name: 'くろしおり',
    frameSrc: '/Entry/Frame/21_Entry_Frame_10.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_10.png',
    iconSrc: '/Modal/icon/22_Modal_icon_10.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_10.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_10.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_10.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_10.png',
    spInfoSrc: '',
    iconAlt: '',
    description: '',
    twitterLink: '',
    youtubeLink: '',
    niconicoLink: '',
    isPublished: true
  },
  {
    index: 11,
    name: 'グラコロ',
    frameSrc: '/Entry/Frame/21_Entry_Frame_11.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_11.png',
    iconSrc: '/Modal/icon/22_Modal_icon_11.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_11.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_11.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_11.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_11.png',
    spInfoSrc: '',
    iconAlt: '',
    description: '',
    twitterLink: '',
    youtubeLink: '',
    niconicoLink: '',
    isPublished: true
  },
  {
    index: 12,
    name: 'さくれい',
    frameSrc: '/Entry/Frame/21_Entry_Frame_12.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_12.png',
    iconSrc: '/Modal/icon/22_Modal_icon_12.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_12.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_12.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_12.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_12.png',
    spInfoSrc: '',
    iconAlt: '',
    description: '',
    twitterLink: '',
    youtubeLink: '',
    niconicoLink: '',
    isPublished: true
  },
  {
    index: 13,
    name: 'Ckiro',
    frameSrc: '/Entry/Frame/21_Entry_Frame_13.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_13.png',
    iconSrc: '/Modal/icon/22_Modal_icon_13.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_13.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_13.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_13.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_13.png',
    spInfoSrc: '',
    iconAlt: '',
    description: '',
    twitterLink: '',
    youtubeLink: '',
    niconicoLink: '',
    isPublished: true
  },
  {
    index: 14,
    name: 'JR根岸線「関内駅」から徒歩5分',
    frameSrc: '/Entry/Frame/21_Entry_Frame_14.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_14.png',
    iconSrc: '/Modal/icon/22_Modal_icon_14.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_14.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_14.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_14.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_14.png',
    spInfoSrc: '',
    iconAlt: '',
    description: '',
    twitterLink: '',
    youtubeLink: '',
    niconicoLink: '',
    isPublished: true
  },
  {
    index: 15,
    name: '菅沼',
    frameSrc: '/Entry/Frame/21_Entry_Frame_15.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_15.png',
    iconSrc: '/Modal/icon/22_Modal_icon_15.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_15.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_15.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_15.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_15.png',
    spInfoSrc: '',
    iconAlt: '',
    description: '',
    twitterLink: '',
    youtubeLink: '',
    niconicoLink: '',
    isPublished: true
  },
  {
    index: 16,
    name: '聖なるバリア －ミラーフォース－',
    frameSrc: '/Entry/Frame/21_Entry_Frame_16.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_16.png',
    iconSrc: '/Modal/icon/22_Modal_icon_16.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_16.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_16.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_16.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_16.png',
    spInfoSrc: '',
    iconAlt: '',
    description: '',
    twitterLink: '',
    youtubeLink: '',
    niconicoLink: '',
    isPublished: true
  },
  {
    index: 17,
    name: '大好きクラブ',
    frameSrc: '/Entry/Frame/21_Entry_Frame_17.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_17.png',
    iconSrc: '/Modal/icon/22_Modal_icon_17.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_17.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_17.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_17.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_17.png',
    spInfoSrc: '',
    iconAlt: '',
    description: '',
    twitterLink: '',
    youtubeLink: '',
    niconicoLink: '',
    isPublished: true
  },
  {
    index: 18,
    name: 'だがしやだがしや',
    frameSrc: '/Entry/Frame/21_Entry_Frame_18.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_18.png',
    iconSrc: '/Modal/icon/22_Modal_icon_18.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_18.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_18.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_18.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_18.png',
    spInfoSrc: '',
    iconAlt: '',
    description: '',
    twitterLink: '',
    youtubeLink: '',
    niconicoLink: '',
    isPublished: true
  },
  {
    index: 19,
    name: '月裏',
    frameSrc: '/Entry/Frame/21_Entry_Frame_19.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_19.png',
    iconSrc: '/Modal/icon/22_Modal_icon_19.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_19.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_19.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_19.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_19.png',
    spInfoSrc: '',
    iconAlt: '',
    description: '',
    twitterLink: '',
    youtubeLink: '',
    niconicoLink: '',
    isPublished: true
  },
  {
    index: 20,
    name: '手稲。',
    frameSrc: '/Entry/Frame/21_Entry_Frame_20.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_20.png',
    iconSrc: '/Modal/icon/22_Modal_icon_20.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_20.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_20.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_20.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_20.png',
    spInfoSrc: '',
    iconAlt: '',
    description: '',
    twitterLink: '',
    youtubeLink: '',
    niconicoLink: '',
    isPublished: true
  },
  {
    index: 21,
    name: 'tokachi',
    frameSrc: '/Entry/Frame/21_Entry_Frame_21.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_21.png',
    iconSrc: '/Modal/icon/22_Modal_icon_21.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_21.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_21.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_21.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_21.png',
    spInfoSrc: '',
    iconAlt: '',
    description: '',
    twitterLink: '',
    youtubeLink: '',
    niconicoLink: '',
    isPublished: true
  },
  {
    index: 22,
    name: 'とそちか',
    frameSrc: '/Entry/Frame/21_Entry_Frame_22.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_22.png',
    iconSrc: '/Modal/icon/22_Modal_icon_22.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_22.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_22.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_22.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_22.png',
    spInfoSrc: '',
    iconAlt: '',
    description: '',
    twitterLink: '',
    youtubeLink: '',
    niconicoLink: '',
    isPublished: true
  },
  {
    index: 23,
    name: 'なぽり',
    frameSrc: '/Entry/Frame/21_Entry_Frame_23.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_23.png',
    iconSrc: '/Modal/icon/22_Modal_icon_23.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_23.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_23.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_23.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_23.png',
    spInfoSrc: '',
    iconAlt: '',
    description: '',
    twitterLink: '',
    youtubeLink: '',
    niconicoLink: '',
    isPublished: true
  },
  {
    index: 24,
    name: 'ネロ',
    frameSrc: '/Entry/Frame/21_Entry_Frame_24.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_24.png',
    iconSrc: '/Modal/icon/22_Modal_icon_24.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_24.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_24.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_24.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_24.png',
    spInfoSrc: '',
    iconAlt: '',
    description: '',
    twitterLink: '',
    youtubeLink: '',
    niconicoLink: '',
    isPublished: true
  },
  {
    index: 25,
    name: '灰色マテリアル',
    frameSrc: '/Entry/Frame/21_Entry_Frame_25.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_25.png',
    iconSrc: '/Modal/icon/22_Modal_icon_25.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_25.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_25.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_25.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_25.png',
    spInfoSrc: '',
    iconAlt: '',
    description: '',
    twitterLink: '',
    youtubeLink: '',
    niconicoLink: '',
    isPublished: true
  },
  {
    index: 26,
    name: 'ハウステンボス',
    frameSrc: '/Entry/Frame/21_Entry_Frame_26.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_26.png',
    iconSrc: '/Modal/icon/22_Modal_icon_26.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_26.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_26.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_26.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_26.png',
    spInfoSrc: '',
    iconAlt: '',
    description: '',
    twitterLink: '',
    youtubeLink: '',
    niconicoLink: '',
    isPublished: true
  },
  {
    index: 27,
    name: 'Happy Machinery',
    frameSrc: '/Entry/Frame/21_Entry_Frame_27.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_27.png',
    iconSrc: '/Modal/icon/22_Modal_icon_27.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_27.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_27.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_27.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_27.png',
    spInfoSrc: '',
    iconAlt: '',
    description: '',
    twitterLink: '',
    youtubeLink: '',
    niconicoLink: '',
    isPublished: true
  },
  {
    index: 28,
    name: 'ばとじっぷ',
    frameSrc: '/Entry/Frame/21_Entry_Frame_28.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_28.png',
    iconSrc: '/Modal/icon/22_Modal_icon_28.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_28.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_28.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_28.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_28.png',
    spInfoSrc: '',
    iconAlt: '',
    description: '',
    twitterLink: '',
    youtubeLink: '',
    niconicoLink: '',
    isPublished: true
  },
  {
    index: 29,
    name: 'Ximco',
    frameSrc: '/Entry/Frame/21_Entry_Frame_29.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_29.png',
    iconSrc: '/Modal/icon/22_Modal_icon_29.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_29.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_29.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_29.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_29.png',
    spInfoSrc: '',
    iconAlt: '',
    description: '',
    twitterLink: '',
    youtubeLink: '',
    niconicoLink: '',
    isPublished: true
  },
  {
    index: 30,
    name: '微熱',
    frameSrc: '/Entry/Frame/21_Entry_Frame_30.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_30.png',
    iconSrc: '/Modal/icon/22_Modal_icon_30.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_30.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_30.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_30.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_30.png',
    spInfoSrc: '',
    iconAlt: '',
    description: '',
    twitterLink: '',
    youtubeLink: '',
    niconicoLink: '',
    isPublished: true
  },
  {
    index: 31,
    name: '水無月☆★',
    frameSrc: '/Entry/Frame/21_Entry_Frame_31.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_31.png',
    iconSrc: '/Modal/icon/22_Modal_icon_31.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_31.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_31.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_31.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_31.png',
    spInfoSrc: '',
    iconAlt: '',
    description: '',
    twitterLink: '',
    youtubeLink: '',
    niconicoLink: '',
    isPublished: true
  },
  {
    index: 32,
    name: 'MUMEI',
    frameSrc: '/Entry/Frame/21_Entry_Frame_32.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_32.png',
    iconSrc: '/Modal/icon/22_Modal_icon_32.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_32.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_32.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_32.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_32.png',
    spInfoSrc: '',
    iconAlt: '',
    description: '',
    twitterLink: '',
    youtubeLink: '',
    niconicoLink: '',
    isPublished: true
  },
  {
    index: 33,
    name: 'メカP',
    frameSrc: '/Entry/Frame/21_Entry_Frame_33.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_33.png',
    iconSrc: '/Modal/icon/22_Modal_icon_33.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_33.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_33.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_33.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_33.png',
    spInfoSrc: '',
    iconAlt: '',
    description: '',
    twitterLink: '',
    youtubeLink: '',
    niconicoLink: '',
    isPublished: true
  },
  {
    index: 34,
    name: 'メスシリンダー',
    frameSrc: '/Entry/Frame/21_Entry_Frame_34.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_34.png',
    iconSrc: '/Modal/icon/22_Modal_icon_34.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_34.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_34.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_34.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_34.png',
    spInfoSrc: '',
    iconAlt: '',
    description: '',
    twitterLink: '',
    youtubeLink: '',
    niconicoLink: '',
    isPublished: true
  },
  {
    index: 35,
    name: 'わたくし氏',
    frameSrc: '/Entry/Frame/21_Entry_Frame_35.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_35.png',
    iconSrc: '/Modal/icon/22_Modal_icon_35.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_35.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_35.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_35.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_35.png',
    spInfoSrc: '',
    iconAlt: '',
    description: '',
    twitterLink: '',
    youtubeLink: '',
    niconicoLink: '',
    isPublished: true
  },
  {
    index: 36,
    name: 'わたぴー',
    frameSrc: '/Entry/Frame/21_Entry_Frame_36.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_36.png',
    iconSrc: '/Modal/icon/22_Modal_icon_36.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_36.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_36.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_36.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_36.png',
    spInfoSrc: '',
    iconAlt: '',
    description: '',
    twitterLink: '',
    youtubeLink: '',
    niconicoLink: '',
    isPublished: true
  },
  {
    index: 37,
    name: 'わっつー',
    frameSrc: '/Entry/Frame/21_Entry_Frame_37.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_37.png',
    iconSrc: '/Modal/icon/22_Modal_icon_37.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_37.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_37.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_37.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_37.png',
    spInfoSrc: '',
    iconAlt: '',
    description: '',
    twitterLink: '',
    youtubeLink: '',
    niconicoLink: '',
    isPublished: true
  },
  {
    index: 38,
    name: '【Kyoro】',
    frameSrc: '/Entry/Frame/21_Entry_Frame_38.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_38.png',
    iconSrc: '/Modal/icon/22_Modal_icon_38.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_38.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_38.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_38.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_38.png',
    spInfoSrc: '',
    iconAlt: '',
    description: '',
    twitterLink: '',
    youtubeLink: '',
    niconicoLink: '',
    isPublished: true
  },
  {
    index: 39,
    name: 'Theas',
    frameSrc: '/Entry/Frame/21_Entry_Frame_39.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_39.png',
    iconSrc: '/Modal/icon/22_Modal_icon_39.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_39.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_39.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_39.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_39.png',
    spInfoSrc: '',
    iconAlt: '',
    description: '',
    twitterLink: '',
    youtubeLink: '',
    niconicoLink: '',
    isPublished: true
  },
  {
    index: 40,
    name: '???',
    frameSrc: '/Entry/Frame/21_Entry_Frame_40_Secret.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_40.png',
    iconSrc: '/Modal/icon/22_Modal_icon_40.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_40_Secret.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_40_secret.png',
    spKirinukiSrc: '',
    spNameSrc: '',
    spInfoSrc: '',
    iconAlt: '',
    description: '',
    twitterLink: '',
    youtubeLink: '',
    niconicoLink: '',
    isPublished: false
  }
];

export default entries;
