export type Entry = {
  index: number;
  name: string;
  frameSrc: string;
  contestantSrc: string;
  iconSrc: string;
  spIconSrc: string;
  spBannerSrc: string;
  spKirinukiSrc: string;
  spNameSrc: string;
  spInfoSrc: string;
  iconAlt: string;
  description: string;
  niconicoLink: string;
  youtubeLink?: string;
  twitterLink: string;
  isPublished: boolean;
};

const entries: Entry[] = [
  {
    index: 1,
    name: '阿保草',
    frameSrc: '/Entry/Frame/21_Entry_Frame_01.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_01.png',
    iconSrc: '/Modal/icon/22_Modal_icon_01.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_01.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_01.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_01.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_01.png',
    spInfoSrc: '',
    iconAlt: '',
    description: '丁寧なアニメ素材YTPMVから勢いのある松岡修造MADまで\n幅広い素材を独自のアイデアで面白く掘り下げる投稿者\nさまざまな作風を使いこなし、従来の音MADを切り開く！',
    niconicoLink: 'https://www.nicovideo.jp/user/45185099',
    youtubeLink: 'https://www.youtube.com/c/ahokusa',
    twitterLink: 'https://twitter.com/leaf_62289',
    isPublished: true
  },
  {
    index: 2,
    name: 'アンデス',
    frameSrc: '/Entry/Frame/21_Entry_Frame_02.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_02.png',
    iconSrc: '/Modal/icon/22_Modal_icon_02.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_02.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_02.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_02.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_02.png',
    spInfoSrc: '',
    iconAlt: '',
    description:
      'インスト曲を中心にクッキー☆で制作し、同界隈を牽引する兄貴\nイキスギな投稿ペースと並行して一人合作を複数回発表している精緻な加工と音作りを得意としており、死角は「ないです」',
    niconicoLink: 'https://www.nicovideo.jp/user/47716345',
    youtubeLink: 'https://www.youtube.com/@AnswerDesk',
    twitterLink: 'https://twitter.com/AnswerDesk_24h',
    isPublished: true
  },
  {
    index: 3,
    name: 'イダルゴ',
    frameSrc: '/Entry/Frame/21_Entry_Frame_03.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_03.png',
    iconSrc: '/Modal/icon/22_Modal_icon_03.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_03.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_03.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_03.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_03.png',
    spInfoSrc: '',
    iconAlt: '',
    description:
      '予測不能の素材と楽曲、謎多き展開で音MADジャンキーを鷲掴み\n驚愕のサイケなビジュアルはこの世界観でしか味わえない\n視聴した後はきっと、目に映る全てがあなたの常識を脅かす！',
    niconicoLink: 'https://www.nicovideo.jp/user/81818168',
    youtubeLink: undefined,
    twitterLink: 'https://twitter.com/hidalgogo852',
    isPublished: true
  },
  {
    index: 4,
    name: '芋タルト',
    frameSrc: '/Entry/Frame/21_Entry_Frame_04.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_04.png',
    iconSrc: '/Modal/icon/22_Modal_icon_04.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_04.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_04.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_04.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_04.png',
    spInfoSrc: '',
    iconAlt: '',
    description:
      'デレマスやダメ万で話題作を輩出しながら、マイナー素材も駆使\n卓越した映像技術に裏打ちされた豪快な仕掛けで魅了する作者\n計算された要素の洪水がぽいすぽぽいすぽすぽすぽいぽいすすぽ',
    niconicoLink: 'https://www.nicovideo.jp/user/64703247',
    youtubeLink: 'https://www.youtube.com/@user-sg9do6xx8b',
    twitterLink: 'https://twitter.com/immortalt_',
    isPublished: true
  },
  {
    index: 5,
    name: 'エロう丸イクイクイクイクイクイク',
    frameSrc: '/Entry/Frame/21_Entry_Frame_05.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_05.png',
    iconSrc: '/Modal/icon/22_Modal_icon_05.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_05.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_05.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_05.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_05.png',
    spInfoSrc: '',
    iconAlt: '',
    description:
      'ゆっくり魔理沙だぜ。今日はこの破壊的作者について説明するぜ\n蚊ルドやムキムキ誠之助など愉快な素材を過剰に演出しているぜ\n【朗報】エロう丸（水地的）の面白さ　ついに限界を突破…',
    niconicoLink: 'https://www.nicovideo.jp/user/95030647',
    youtubeLink: undefined,
    twitterLink: 'https://twitter.com/pic65233129',
    isPublished: true
  },
  {
    index: 6,
    name: 'KAISATSU',
    frameSrc: '/Entry/Frame/21_Entry_Frame_06.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_06.png',
    iconSrc: '/Modal/icon/22_Modal_icon_06.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_06.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_06.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_06.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_06.png',
    spInfoSrc: '',
    iconAlt: '',
    description:
      '元気が出る正統派松岡修造MADを送り出してきたベテラン投稿者\n人物を深く掘り下げるセリフ選びや替え歌、人力を得意とする\n濃いストーリーが紡がれる、情熱あふれる動画で熱くなれ！',
    niconicoLink: 'https://www.nicovideo.jp/user/2153500',
    youtubeLink: undefined,
    twitterLink: 'https://twitter.com/kai_satsu',
    isPublished: true
  },
  {
    index: 7,
    name: 'カスk°',
    frameSrc: '/Entry/Frame/21_Entry_Frame_07.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_07.png',
    iconSrc: '/Modal/icon/22_Modal_icon_07.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_07.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_07.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_07.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_07.png',
    spInfoSrc: '',
    iconAlt: '',
    description:
      'マリオシリーズを素材とした賑やかな音MADを得意とする作者\n複数タイトルを横断してキャラやアイテムが飛び交うさまは圧巻\n歴史をたどるように、素材たちがところ狭しと暴れまわる！',
    niconicoLink: 'https://www.nicovideo.jp/user/42685196',
    youtubeLink: undefined,
    twitterLink: 'https://twitter.com/aruxash',
    isPublished: true
  },
  {
    index: 8,
    name: '神酒',
    frameSrc: '/Entry/Frame/21_Entry_Frame_08.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_08.png',
    iconSrc: '/Modal/icon/22_Modal_icon_08.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_08.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_08.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_08.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_08.png',
    spInfoSrc: '',
    iconAlt: '',
    description:
      '「エルシャダイ」から「ゆゆゆ」果ては「阿部サダヲ」まで\n広範囲の素材を扱いつつ、音MADの根底を覆し続けてきた作者\n綿密な作為とその実現へかける技術に、参りましたーっ！',
    niconicoLink: 'https://www.nicovideo.jp/user/59897810',
    youtubeLink: undefined,
    twitterLink: 'https://twitter.com/kami_zake',
    isPublished: true
  },
  {
    index: 9,
    name: '♪くらっち♪',
    frameSrc: '/Entry/Frame/21_Entry_Frame_09.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_09.png',
    iconSrc: '/Modal/icon/22_Modal_icon_09.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_09.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_09.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_09.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_09.png',
    spInfoSrc: '',
    iconAlt: '',
    description:
      'アニメ・芸人などを巧みに操り素材の味を引き立てる作風の傍ら\nZ会・クンナ・真島茂樹などの音MADらしい素材でも盛り上げる\n背後から近づいてくるもう一人の仲間とどんな道を進むのか！',
    niconicoLink: 'https://www.nicovideo.jp/user/23413611',
    youtubeLink: 'https://www.youtube.com/@kuratti2525',
    twitterLink: 'https://twitter.com/kuratti2525',
    isPublished: true
  },
  {
    index: 10,
    name: 'くろしおり',
    frameSrc: '/Entry/Frame/21_Entry_Frame_10.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_10.png',
    iconSrc: '/Modal/icon/22_Modal_icon_10.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_10.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_10.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_10.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_10.png',
    spInfoSrc: '',
    iconAlt: '',
    description: '',
    niconicoLink: 'https://www.nicovideo.jp/user/16417282',
    youtubeLink: 'https://www.youtube.com/@9640l1',
    twitterLink: 'https://twitter.com/kr4oli',
    isPublished: true
  },
  {
    index: 11,
    name: 'グラコロ',
    frameSrc: '/Entry/Frame/21_Entry_Frame_11.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_11.png',
    iconSrc: '/Modal/icon/22_Modal_icon_11.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_11.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_11.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_11.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_11.png',
    spInfoSrc: '',
    iconAlt: '',
    description:
      '抜群のセリフ合わせで、作品愛のあるMADを投稿する作者\n投稿初期はアルカプを、近年ではにじさんじをメイン素材に\n人気キャラクターたちを音MADの舞台で魅力的に輝かせる！',
    niconicoLink: 'https://www.nicovideo.jp/user/13783788',
    youtubeLink: 'https://www.youtube.com/@user-to1se6so8ll',
    twitterLink: 'https://twitter.com/komugi_gkk',
    isPublished: true
  },
  {
    index: 12,
    name: 'さくれい',
    frameSrc: '/Entry/Frame/21_Entry_Frame_12.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_12.png',
    iconSrc: '/Modal/icon/22_Modal_icon_12.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_12.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_12.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_12.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_12.png',
    spInfoSrc: '',
    iconAlt: '',
    description:
      'テーマオールスター・数々の合作で様々な素材を華麗に捌きつつ\nYouTuber・恋愛サーキュレーションMADでの活躍も周知の事実\nノンストップでオシャ連続投稿する作者の動画は進化し続ける！',
    niconicoLink: 'https://www.nicovideo.jp/user/55975521',
    youtubeLink: 'https://www.youtube.com/@sakurei_2015',
    twitterLink: 'https://twitter.com/sakurei_2015',
    isPublished: true
  },
  {
    index: 13,
    name: 'Ckiro',
    frameSrc: '/Entry/Frame/21_Entry_Frame_13.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_13.png',
    iconSrc: '/Modal/icon/22_Modal_icon_13.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_13.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_13.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_13.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_13.png',
    spInfoSrc: '',
    iconAlt: '',
    description: '',
    niconicoLink: 'https://www.nicovideo.jp/user/11076215',
    youtubeLink: undefined,
    twitterLink: 'https://twitter.com/Ckirored',
    isPublished: true
  },
  {
    index: 14,
    name: 'JR根岸線「関内駅」から徒歩5分',
    frameSrc: '/Entry/Frame/21_Entry_Frame_14.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_14.png',
    iconSrc: '/Modal/icon/22_Modal_icon_14.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_14.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_14.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_14.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_14.png',
    spInfoSrc: '',
    iconAlt: '',
    description:
      'レスリングシリーズ、中でもヒロミとアメゲイを多用する兄貴は\nどんな糸口も音MADの面白さへと昇華する歪みねえ発想の持ち主\n"斉藤洋子式"をも生み出した、誰も真似できない着眼点が光る！',
    niconicoLink: 'https://www.nicovideo.jp/user/6070737',
    youtubeLink: 'https://www.youtube.com/@JR-uj6kc',
    twitterLink: 'https://twitter.com/kannai',
    isPublished: true
  },
  {
    index: 15,
    name: '菅沼',
    frameSrc: '/Entry/Frame/21_Entry_Frame_15.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_15.png',
    iconSrc: '/Modal/icon/22_Modal_icon_15.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_15.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_15.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_15.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_15.png',
    spInfoSrc: '',
    iconAlt: '',
    description:
      'ディープなアニメから軽快な芸人ネタまで網羅的に扱う作者\n制作の雰囲気に合わせ表現手法も使い分けるストイックな姿勢が\nコンビでどう展開するのか、見逃すわけにはいかないじゃんよ！',
    niconicoLink: 'https://www.nicovideo.jp/user/17938670',
    youtubeLink: undefined,
    twitterLink: 'https://twitter.com/suganumafuyu',
    isPublished: true
  },
  {
    index: 16,
    name: '聖なるバリア －ミラーフォース－',
    frameSrc: '/Entry/Frame/21_Entry_Frame_16.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_16.png',
    iconSrc: '/Modal/icon/22_Modal_icon_16.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_16.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_16.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_16.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_16.png',
    spInfoSrc: '',
    iconAlt: '',
    description:
      '配信者をメインに音MADを制作する作者だけどなんだアレ！？\n近年では「曲が素材シリーズ」や映像メイカーとしても有名に\n発想も技術も兼ね備えた罠カードが、音MDM天を破壊する！',
    niconicoLink: 'https://www.nicovideo.jp/user/38110073',
    youtubeLink: 'https://www.youtube.com/@Mirror_Force',
    twitterLink: 'https://twitter.com/c44095762',
    isPublished: true
  },
  {
    index: 17,
    name: '大好きクラブ',
    frameSrc: '/Entry/Frame/21_Entry_Frame_17.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_17.png',
    iconSrc: '/Modal/icon/22_Modal_icon_17.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_17.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_17.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_17.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_17.png',
    spInfoSrc: '',
    iconAlt: '',
    description: '',
    niconicoLink: 'https://www.nicovideo.jp/user/64924825',
    youtubeLink: 'https://www.youtube.com/@user-ks9hf8bx1l',
    twitterLink: 'https://twitter.com/niggerofpokemon',
    isPublished: true
  },
  {
    index: 18,
    name: 'だがしやだがしや',
    frameSrc: '/Entry/Frame/21_Entry_Frame_18.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_18.png',
    iconSrc: '/Modal/icon/22_Modal_icon_18.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_18.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_18.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_18.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_18.png',
    spInfoSrc: '',
    iconAlt: '',
    description:
      'ジャンルを問わずキレのある重厚な音声をくみ上げる作者\n往年のアニメ・実写素材へ新たに息を吹き込み、その技量を実証\n投稿歴の新しい音MAD革命児が先陣を切って走り抜ける！',
    niconicoLink: 'https://www.nicovideo.jp/user/96159684',
    youtubeLink: 'https://www.youtube.com/@user-xj1wb9xh3l',
    twitterLink: 'https://twitter.com/dagadagashi_',
    isPublished: true
  },
  {
    index: 19,
    name: '月裏',
    frameSrc: '/Entry/Frame/21_Entry_Frame_19.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_19.png',
    iconSrc: '/Modal/icon/22_Modal_icon_19.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_19.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_19.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_19.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_19.png',
    spInfoSrc: '',
    iconAlt: '',
    description:
      '質感のある音色と流麗な映像を構築し、視聴者を魅了する\nキャラクターに着目し柔軟に作風を適応できる対応力も第一級\n意欲的な作曲活動も支持を集める今、したたかに爆発していく！',
    niconicoLink: 'https://www.nicovideo.jp/user/24455542',
    youtubeLink: 'https://www.youtube.com/@Tsukiri',
    twitterLink: 'https://twitter.com/tsukiri_0112',
    isPublished: true
  },
  {
    index: 20,
    name: '手稲。',
    frameSrc: '/Entry/Frame/21_Entry_Frame_20.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_20.png',
    iconSrc: '/Modal/icon/22_Modal_icon_20.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_20.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_20.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_20.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_20.png',
    spInfoSrc: '',
    iconAlt: '',
    description: '',
    niconicoLink: 'https://www.nicovideo.jp/user/57671569',
    youtubeLink: 'https://www.youtube.com/@Teine.',
    twitterLink: 'https://twitter.com/Inaho_Inadumi',
    isPublished: true
  },
  {
    index: 21,
    name: 'tokachi',
    frameSrc: '/Entry/Frame/21_Entry_Frame_21.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_21.png',
    iconSrc: '/Modal/icon/22_Modal_icon_21.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_21.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_21.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_21.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_21.png',
    spInfoSrc: '',
    iconAlt: '',
    description: '',
    niconicoLink: 'https://www.nicovideo.jp/user/21523375',
    youtubeLink: 'https://www.youtube.com/@tokachi9175',
    twitterLink: 'https://twitter.com/tokachi_12',
    isPublished: true
  },
  {
    index: 22,
    name: 'とそちか',
    frameSrc: '/Entry/Frame/21_Entry_Frame_22.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_22.png',
    iconSrc: '/Modal/icon/22_Modal_icon_22.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_22.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_22.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_22.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_22.png',
    spInfoSrc: '',
    iconAlt: '',
    description: '',
    niconicoLink: 'https://www.nicovideo.jp/user/46721826',
    youtubeLink: 'https://www.youtube.com/@tosochika705',
    twitterLink: 'https://twitter.com/tosochika',
    isPublished: true
  },
  {
    index: 23,
    name: 'なぽり',
    frameSrc: '/Entry/Frame/21_Entry_Frame_23.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_23.png',
    iconSrc: '/Modal/icon/22_Modal_icon_23.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_23.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_23.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_23.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_23.png',
    spInfoSrc: '',
    iconAlt: '',
    description: '',
    niconicoLink: 'https://www.nicovideo.jp/user/47562461',
    youtubeLink: 'https://www.youtube.com/@user-dj7ex4sh3c',
    twitterLink: 'https://twitter.com/napolythm',
    isPublished: true
  },
  {
    index: 24,
    name: 'ネロ',
    frameSrc: '/Entry/Frame/21_Entry_Frame_24.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_24.png',
    iconSrc: '/Modal/icon/22_Modal_icon_24.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_24.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_24.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_24.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_24.png',
    spInfoSrc: '',
    iconAlt: '',
    description: 'エルシャダイMADの全盛期を支えた経歴もありつつ\n現在はジョジョMADにおいてヒット作を多数輩出\n最前線から魅せる、上質な構成力のラッシュをとくと見よ！',
    niconicoLink: 'https://www.nicovideo.jp/user/14666489',
    youtubeLink: 'https://www.youtube.com/@Nero_JOJO',
    twitterLink: 'https://twitter.com/Nero_JOJO',
    isPublished: true
  },
  {
    index: 25,
    name: '灰色マテリアル',
    frameSrc: '/Entry/Frame/21_Entry_Frame_25.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_25.png',
    iconSrc: '/Modal/icon/22_Modal_icon_25.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_25.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_25.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_25.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_25.png',
    spInfoSrc: '',
    iconAlt: '',
    description:
      'FF7、特にセフィロスに注目したファンアート的音MADを筆頭に\nゆめにっきMADや私的オールスターでもクールな雰囲気が魅力\n"いろいろな素材で"奏でる作者のアルテマウェポンが飛び出す！',
    niconicoLink: 'https://www.nicovideo.jp/user/42324428',
    youtubeLink: 'https://www.youtube.com/@Haiiro_Material',
    twitterLink: 'https://twitter.com/otomad2023',
    isPublished: true
  },
  {
    index: 26,
    name: 'ハウステンボス',
    frameSrc: '/Entry/Frame/21_Entry_Frame_26.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_26.png',
    iconSrc: '/Modal/icon/22_Modal_icon_26.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_26.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_26.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_26.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_26.png',
    spInfoSrc: '',
    iconAlt: '',
    description:
      '名前に反してディズニー関連の実写・アニメ素材を中心に扱い\n心地よいセリフ合わせと独特の空気感を武器に夢の世界を演出\n"これから皆さんを神秘的な素晴らしい旅にご案内します。"',
    niconicoLink: 'https://www.nicovideo.jp/user/86291784',
    youtubeLink: undefined,
    twitterLink: 'https://twitter.com/zyankenbaka',
    isPublished: true
  },
  {
    index: 27,
    name: 'Happy Machinery',
    frameSrc: '/Entry/Frame/21_Entry_Frame_27.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_27.png',
    iconSrc: '/Modal/icon/22_Modal_icon_27.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_27.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_27.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_27.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_27.png',
    spInfoSrc: '',
    iconAlt: '',
    description:
      'カワイイ・カッコイイ・スタイリッシュなクッキー☆映像の達人\n「NYD2019」での『Big Brother』パートは後世に影響を与えた\n3Dからアニメーションまで幅広く表現を活かした職人芸が唸る！',
    niconicoLink: 'https://www.nicovideo.jp/user/37501628',
    youtubeLink: 'https://www.youtube.com/@happymachinery1342',
    twitterLink: 'https://twitter.com/hapimashi0131',
    isPublished: true
  },
  {
    index: 28,
    name: 'ばとじっぷ',
    frameSrc: '/Entry/Frame/21_Entry_Frame_28.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_28.png',
    iconSrc: '/Modal/icon/22_Modal_icon_28.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_28.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_28.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_28.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_28.png',
    spInfoSrc: '',
    iconAlt: '',
    description:
      'ウ ン チ ー コ ン グ は音MADファンに限らず人気の超ヒット\n素材の手広さと引き出しの多さは、私的オールスターでも大暴れ\n目も耳もいっぱいになるおびただしい量の情報が走ｒ…走る～！',
    niconicoLink: 'https://www.nicovideo.jp/user/27636552',
    youtubeLink: undefined,
    twitterLink: 'https://twitter.com/BATO_Zip',
    isPublished: true
  },
  {
    index: 29,
    name: 'Ximco',
    frameSrc: '/Entry/Frame/21_Entry_Frame_29.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_29.png',
    iconSrc: '/Modal/icon/22_Modal_icon_29.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_29.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_29.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_29.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_29.png',
    spInfoSrc: '',
    iconAlt: '',
    description: '多くのジャンルを扱える、マルチな技術を持ち合わせた作者\n知的アプローチで詰めこまれたオールスターMADを確立\n四方八方から繰り出される、体系的音MADネタで包み込む！',
    niconicoLink: 'https://www.nicovideo.jp/user/50136284',
    youtubeLink: 'https://www.youtube.com/@ximco_yuzurihaamane',
    twitterLink: 'https://twitter.com/__Ximco__',
    isPublished: true
  },
  {
    index: 30,
    name: '微熱',
    frameSrc: '/Entry/Frame/21_Entry_Frame_30.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_30.png',
    iconSrc: '/Modal/icon/22_Modal_icon_30.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_30.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_30.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_30.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_30.png',
    spInfoSrc: '',
    iconAlt: '',
    description:
      'イーノックなどを素材にアグレッシブな作品を投稿する一方で\n心の籠もった人力や気持ち良いセリフ合わせなど高い技術も披露\n合作でも画期的なパートを多数制作する作者の、宴の始まりだ！',
    niconicoLink: 'https://www.nicovideo.jp/user/16151608',
    youtubeLink: undefined,
    twitterLink: 'https://twitter.com/binetsu0904',
    isPublished: true
  },
  {
    index: 31,
    name: '水無月☆★',
    frameSrc: '/Entry/Frame/21_Entry_Frame_31.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_31.png',
    iconSrc: '/Modal/icon/22_Modal_icon_31.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_31.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_31.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_31.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_31.png',
    spInfoSrc: '',
    iconAlt: '',
    description: '',
    niconicoLink: 'https://www.nicovideo.jp/user/25521306',
    youtubeLink: undefined,
    twitterLink: 'https://twitter.com/6June_',
    isPublished: true
  },
  {
    index: 32,
    name: 'MUMEI',
    frameSrc: '/Entry/Frame/21_Entry_Frame_32.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_32.png',
    iconSrc: '/Modal/icon/22_Modal_icon_32.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_32.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_32.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_32.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_32.png',
    spInfoSrc: '',
    iconAlt: '',
    description:
      'アイドルマスターをはじめ、ウマ娘・VTuberなどに想いを詰めて\n公式かと見紛う驚異の作り込みで人気コンテンツのファンも納得\n数多くのヒット作を擁する投稿者が、満を持して舞台に立つ！',
    niconicoLink: 'https://www.nicovideo.jp/user/17598990',
    youtubeLink: 'https://www.youtube.com/@MrMUMEI',
    twitterLink: 'https://twitter.com/mumeiburogu',
    isPublished: true
  },
  {
    index: 33,
    name: 'メカP',
    frameSrc: '/Entry/Frame/21_Entry_Frame_33.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_33.png',
    iconSrc: '/Modal/icon/22_Modal_icon_33.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_33.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_33.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_33.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_33.png',
    spInfoSrc: '',
    iconAlt: '',
    description:
      'アイマスMADの歴史に名を残す人力＆替え歌といえばこの作者\n「除夜m@s」も有名だが、令和に入ってからもヒット作を連発\n有名歌手にもスペシャルサンクスされるお家芸が炸裂する！',
    niconicoLink: 'https://www.nicovideo.jp/user/3963070',
    youtubeLink: 'https://www.youtube.com/@user-yi8qw3jo2q',
    twitterLink: 'https://twitter.com/mekapi',
    isPublished: true
  },
  {
    index: 34,
    name: 'メスシリンダー',
    frameSrc: '/Entry/Frame/21_Entry_Frame_34.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_34.png',
    iconSrc: '/Modal/icon/22_Modal_icon_34.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_34.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_34.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_34.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_34.png',
    spInfoSrc: '',
    iconAlt: '',
    description:
      'ニコニコメドレーを日本一投稿している圧倒的アウトプット量\nそこで培われたアレンジ・構成力が音MADにも発揮されている\n多種多様な素材を操り、視聴者を新しい世界にいざなう！',
    niconicoLink: 'https://www.nicovideo.jp/user/82669020',
    youtubeLink: undefined,
    twitterLink: 'https://twitter.com/mesushirinda',
    isPublished: true
  },
  {
    index: 35,
    name: 'わたくし氏',
    frameSrc: '/Entry/Frame/21_Entry_Frame_35.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_35.png',
    iconSrc: '/Modal/icon/22_Modal_icon_35.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_35.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_35.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_35.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_35.png',
    spInfoSrc: '',
    iconAlt: '',
    description: 'Vtuberからスパイダーマ、様々な素材に手を伸ばし\nそのどれもコントロールする技量を持つ期待の新星\n「わたくし」的センスでフレッシュな旋風を巻き起こす！',
    niconicoLink: 'https://www.nicovideo.jp/user/93606868',
    youtubeLink: 'https://www.youtube.com/@user-gs9ru2nb8l',
    twitterLink: 'https://twitter.com/watakushiiiii',
    isPublished: true
  },
  {
    index: 36,
    name: 'わたぴー',
    frameSrc: '/Entry/Frame/21_Entry_Frame_36.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_36.png',
    iconSrc: '/Modal/icon/22_Modal_icon_36.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_36.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_36.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_36.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_36.png',
    spInfoSrc: '',
    iconAlt: '',
    description:
      'ひとつの自慢話、一枚の画像から無限の可能性を引き出す作者で\n小道具はもちろんゲームまで自作し、なんと家族の姿まで活用\nあらゆるギミックを使いこなし、素材に命を吹き込む！',
    niconicoLink: 'https://www.nicovideo.jp/user/58026723',
    youtubeLink: undefined,
    twitterLink: 'https://twitter.com/watapy_jiman',
    isPublished: true
  },
  {
    index: 37,
    name: 'わっつー',
    frameSrc: '/Entry/Frame/21_Entry_Frame_37.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_37.png',
    iconSrc: '/Modal/icon/22_Modal_icon_37.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_37.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_37.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_37.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_37.png',
    spInfoSrc: '',
    iconAlt: '',
    description:
      'ドナルドを素材にYTPMV、替え歌人力など正統派MADを制作\n歴史ある素材にも関わらず真摯に作り続け評価される実力者\nYouTubeからも支持されている作者が、時代を塗り替える！',
    niconicoLink: 'https://www.nicovideo.jp/user/96040263',
    youtubeLink: 'https://www.youtube.com/@mcd_0101',
    twitterLink: 'https://twitter.com/Watu0720',
    isPublished: true
  },
  {
    index: 38,
    name: '【Kyoro】',
    frameSrc: '/Entry/Frame/21_Entry_Frame_38.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_38.png',
    iconSrc: '/Modal/icon/22_Modal_icon_38.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_38.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_38.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_38.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_38.png',
    spInfoSrc: '',
    iconAlt: '',
    description:
      '百地たまてを中心にアニメ系素材のYTPMVをハイペースで制作\nYouTubeでも人気を博しており、様々な合作にも精力的に参加\n玉手箱を由来にした色とりどりのテクニックが繰り出される！',
    niconicoLink: 'https://www.nicovideo.jp/user/48539410',
    youtubeLink: 'https://www.youtube.com/@_m_m_t___t_m_t_',
    twitterLink: 'https://twitter.com/_m_m_t___t_m_t_',
    isPublished: true
  },
  {
    index: 39,
    name: 'Theas',
    frameSrc: '/Entry/Frame/21_Entry_Frame_39.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_39.png',
    iconSrc: '/Modal/icon/22_Modal_icon_39.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_39.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_39.png',
    spKirinukiSrc: '/SP/Entry_Detail/Kirinuki/s22_Entry_Kirinuki_39.png',
    spNameSrc: '/SP/Entry_Detail/Name/s22_Entry_name_39.png',
    spInfoSrc: '',
    iconAlt: '',
    description:
      'アニメ系や「曲が素材シリーズ」音MADを得意としながらも\n円周率、シャトルランなど森羅万象を素材にする守備範囲の広さ\n破竹の勢いで投稿する作者が"論理、拳、闘志　勝利ですわ！"',
    niconicoLink: 'https://www.nicovideo.jp/user/68814922',
    youtubeLink: 'https://www.youtube.com/@Theas_',
    twitterLink: 'https://twitter.com/The_a_second',
    isPublished: true
  },
  {
    index: 40,
    name: '???',
    frameSrc: '/Entry/Frame/21_Entry_Frame_40_Secret.png',
    contestantSrc: '/Modal/contestants/22_Modal_contestant_40.png',
    iconSrc: '/Modal/icon/22_Modal_icon_40.png',
    spIconSrc: '/SP/Entry_Detail/Icon/s22_EntryIcon_40_Secret.png',
    spBannerSrc: '/SP/Entry/Banner/s21_EntryIndex_Banner_40_secret.png',
    spKirinukiSrc: '',
    spNameSrc: '',
    spInfoSrc: '',
    iconAlt: '',
    description: '',
    niconicoLink: 'https://www.nicovideo.jp/user/47566407',
    youtubeLink: 'https://www.youtube.com/@user-ox8wz7xm2y',
    twitterLink: 'https://twitter.com/ono_natchet',
    isPublished: false
  }
];

export default entries;
