export type Pair = {
  index: number;
  name: string;
  frameSrc: string;
  hnASrc: string;
  hnBSrc: string;
  illustSrc: string;
  nameSrc: string;
  spIconSrc: string;
  spBannerSrc: string;
  spKirinukiSrc: string;
  spNameSrc: string;
  spBaseASrc: string;
  spBaseBSrc: string;
  description: string;
  isPublished: boolean;
};

const pairs: Pair[] = [
  {
    index: 1,
    name: 'Senpai Club',
    frameSrc: '/Pair/Frame/31_Pair_Frame_01.png',
    hnASrc: '/Pair_Modal/HN/32_Pair_Modal_HN_01A.png',
    hnBSrc: '/Pair_Modal/HN/32_Pair_Modal_HN_01B.png',
    illustSrc: '/Pair_Modal/Illust/32_Pair_Modal_Illust_01.png',
    nameSrc: '/Pair_Modal/Name/32_Pair_Modal_Name_01.png',
    spIconSrc: '/SP/Pair_Detail/Icon/s32_PairIcon_01.png',
    spBannerSrc: '/SP/Pair/Banner/s21_PairIndex_Banner_01.png',
    spKirinukiSrc: '/SP/Pair_Detail/Kirinuki/s32_Entry_Kirinuki_01.png',
    spNameSrc: '/SP/Pair_Detail/Name/s32_Pair_name_01.png',
    spBaseASrc: '/SP/Pair_Detail/HNBase/s32_Pair_HNBase_01_A.png',
    spBaseBSrc: '/SP/Pair_Detail/HNBase/s32_Pair_HNBase_01_B.png',
    description: '音声・映像 技巧派の二人がコンビ結成\n積み上げたノウハウをどう凌駕する！？',
    isPublished: true
  },
  {
    index: 2,
    name: 'グラスハウス',
    frameSrc: '/Pair/Frame/31_Pair_Frame_02.png',
    hnASrc: '/Pair_Modal/HN/32_Pair_Modal_HN_02A.png',
    hnBSrc: '/Pair_Modal/HN/32_Pair_Modal_HN_02B.png',
    illustSrc: '/Pair_Modal/Illust/32_Pair_Modal_Illust_02.png',
    nameSrc: '/Pair_Modal/Name/32_Pair_Modal_Name_02.png',
    spIconSrc: '/SP/Pair_Detail/Icon/s32_PairIcon_02.png',
    spBannerSrc: '/SP/Pair/Banner/s21_PairIndex_Banner_02.png',
    spKirinukiSrc: '/SP/Pair_Detail/Kirinuki/s32_Entry_Kirinuki_02.png',
    spNameSrc: '/SP/Pair_Detail/Name/s32_Pair_name_02.png',
    spBaseASrc: '/SP/Pair_Detail/HNBase/s32_Pair_HNBase_02_A.png',
    spBaseBSrc: '/SP/Pair_Detail/HNBase/s32_Pair_HNBase_02_B.png',
    description: '好きなコンテンツへ実直に向き合う二人を\n結びつける動画は？放送まで乞うご期待！',
    isPublished: true
  },
  {
    index: 3,
    name: '+++v',
    frameSrc: '/Pair/Frame/31_Pair_Frame_03.png',
    hnASrc: '/Pair_Modal/HN/32_Pair_Modal_HN_03A.png',
    hnBSrc: '/Pair_Modal/HN/32_Pair_Modal_HN_03B.png',
    illustSrc: '/Pair_Modal/Illust/32_Pair_Modal_Illust_03.png',
    nameSrc: '/Pair_Modal/Name/32_Pair_Modal_Name_03.png',
    spIconSrc: '/SP/Pair_Detail/Icon/s32_PairIcon_03.png',
    spBannerSrc: '/SP/Pair/Banner/s21_PairIndex_Banner_03.png',
    spKirinukiSrc: '/SP/Pair_Detail/Kirinuki/s32_Entry_Kirinuki_03.png',
    spNameSrc: '/SP/Pair_Detail/Name/s32_Pair_name_03.png',
    spBaseASrc: '/SP/Pair_Detail/HNBase/s32_Pair_HNBase_03_A.png',
    spBaseBSrc: '/SP/Pair_Detail/HNBase/s32_Pair_HNBase_03_B.png',
    description: '超・広範囲の視野と手腕を持つ二人の\nスペクタクルにあなたも没頭する！？',
    isPublished: true
  },
  {
    index: 4,
    name: 'バリaThion',
    frameSrc: '/Pair/Frame/31_Pair_Frame_04.png',
    hnASrc: '/Pair_Modal/HN/32_Pair_Modal_HN_04A.png',
    hnBSrc: '/Pair_Modal/HN/32_Pair_Modal_HN_04B.png',
    illustSrc: '/Pair_Modal/Illust/32_Pair_Modal_Illust_04.png',
    nameSrc: '/Pair_Modal/Name/32_Pair_Modal_Name_04.png',
    spIconSrc: '/SP/Pair_Detail/Icon/s32_PairIcon_04.png',
    spBannerSrc: '/SP/Pair/Banner/s21_PairIndex_Banner_04.png',
    spKirinukiSrc: '/SP/Pair_Detail/Kirinuki/s32_Entry_Kirinuki_04.png',
    spNameSrc: '/SP/Pair_Detail/Name/s32_Pair_name_04.png',
    spBaseASrc: '/SP/Pair_Detail/HNBase/s32_Pair_HNBase_04_A.png',
    spBaseBSrc: '/SP/Pair_Detail/HNBase/s32_Pair_HNBase_04_B.png',
    description: '現代を語るに欠かせない二人がコンビ結成\n重なり合うセッションに、皆酔いしれる！',
    isPublished: true
  },
  {
    index: 5,
    name: '堀り鉄',
    frameSrc: '/Pair/Frame/31_Pair_Frame_05.png',
    hnASrc: '/Pair_Modal/HN/32_Pair_Modal_HN_05A.png',
    hnBSrc: '/Pair_Modal/HN/32_Pair_Modal_HN_05B.png',
    illustSrc: '/Pair_Modal/Illust/32_Pair_Modal_Illust_05.png',
    nameSrc: '/Pair_Modal/Name/32_Pair_Modal_Name_05.png',
    spIconSrc: '/SP/Pair_Detail/Icon/s32_PairIcon_05.png',
    spBannerSrc: '/SP/Pair/Banner/s21_PairIndex_Banner_05.png',
    spKirinukiSrc: '/SP/Pair_Detail/Kirinuki/s32_Entry_Kirinuki_05.png',
    spNameSrc: '/SP/Pair_Detail/Name/s32_Pair_name_05.png',
    spBaseASrc: '/SP/Pair_Detail/HNBase/s32_Pair_HNBase_05_A.png',
    spBaseBSrc: '/SP/Pair_Detail/HNBase/s32_Pair_HNBase_05_B.png',
    description: '異なるジャンルで活動する二人が連結！\nコンビの目指す先まで、乗り遅れるな！',
    isPublished: true
  },
  {
    index: 6,
    name: 'とそちか',
    frameSrc: '/Pair/Frame/31_Pair_Frame_06.png',
    hnASrc: '/Pair_Modal/HN/32_Pair_Modal_HN_06A.png',
    hnBSrc: '/Pair_Modal/HN/32_Pair_Modal_HN_06B.png',
    illustSrc: '/Pair_Modal/Illust/32_Pair_Modal_Illust_06.png',
    nameSrc: '/Pair_Modal/Name/32_Pair_Modal_Name_06.png',
    spIconSrc: '/SP/Pair_Detail/Icon/s32_PairIcon_06.png',
    spBannerSrc: '/SP/Pair/Banner/s21_PairIndex_Banner_06.png',
    spKirinukiSrc: '/SP/Pair_Detail/Kirinuki/s32_Entry_Kirinuki_06.png',
    spNameSrc: '/SP/Pair_Detail/Name/s32_Pair_name_06.png',
    spBaseASrc: '/SP/Pair_Detail/HNBase/s32_Pair_HNBase_06_A.png',
    spBaseBSrc: '/SP/Pair_Detail/HNBase/s32_Pair_HNBase_06_B.png',
    description: '計算高い目線から練られたアイデアを駆使し\n音MADの構造をどう組み立てるのか！？',
    isPublished: true
  },
  {
    index: 7,
    name: '二○二○からの使者',
    frameSrc: '/Pair/Frame/31_Pair_Frame_07.png',
    hnASrc: '/Pair_Modal/HN/32_Pair_Modal_HN_07A.png',
    hnBSrc: '/Pair_Modal/HN/32_Pair_Modal_HN_07B.png',
    illustSrc: '/Pair_Modal/Illust/32_Pair_Modal_Illust_07.png',
    nameSrc: '/Pair_Modal/Name/32_Pair_Modal_Name_07.png',
    spIconSrc: '/SP/Pair_Detail/Icon/s32_PairIcon_07.png',
    spBannerSrc: '/SP/Pair/Banner/s21_PairIndex_Banner_07.png',
    spKirinukiSrc: '/SP/Pair_Detail/Kirinuki/s32_Entry_Kirinuki_07.png',
    spNameSrc: '/SP/Pair_Detail/Name/s32_Pair_name_07.png',
    spBaseASrc: '/SP/Pair_Detail/HNBase/s32_Pair_HNBase_07_A.png',
    spBaseBSrc: '/SP/Pair_Detail/HNBase/s32_Pair_HNBase_07_B.png',
    description: 'ベテラン素材を駆使するニューカマー同士\n手を組んだ！音MDM天に吹かせ新風！',
    isPublished: true
  },
  {
    index: 8,
    name: 'Team C☆',
    frameSrc: '/Pair/Frame/31_Pair_Frame_08.png',
    hnASrc: '/Pair_Modal/HN/32_Pair_Modal_HN_08A.png',
    hnBSrc: '/Pair_Modal/HN/32_Pair_Modal_HN_08B.png',
    illustSrc: '/Pair_Modal/Illust/32_Pair_Modal_Illust_08.png',
    nameSrc: '/Pair_Modal/Name/32_Pair_Modal_Name_08.png',
    spIconSrc: '/SP/Pair_Detail/Icon/s32_PairIcon_08.png',
    spBannerSrc: '/SP/Pair/Banner/s21_PairIndex_Banner_08.png',
    spKirinukiSrc: '/SP/Pair_Detail/Kirinuki/s32_Entry_Kirinuki_08.png',
    spNameSrc: '/SP/Pair_Detail/Name/s32_Pair_name_08.png',
    spBaseASrc: '/SP/Pair_Detail/HNBase/s32_Pair_HNBase_08_A.png',
    spBaseBSrc: '/SP/Pair_Detail/HNBase/s32_Pair_HNBase_08_B.png',
    description: '二人の動画は常に第一線をリード！\n誰も彼もが盛り上がること間違いなし！',
    isPublished: true
  },
  {
    index: 9,
    name: '8116°の二人にご用心 ~Beware the cascade of material~',
    frameSrc: '/Pair/Frame/31_Pair_Frame_09.png',
    hnASrc: '/Pair_Modal/HN/32_Pair_Modal_HN_09A.png',
    hnBSrc: '/Pair_Modal/HN/32_Pair_Modal_HN_09B.png',
    illustSrc: '/Pair_Modal/Illust/32_Pair_Modal_Illust_09.png',
    nameSrc: '/Pair_Modal/Name/32_Pair_Modal_Name_09.png',
    spIconSrc: '/SP/Pair_Detail/Icon/s32_PairIcon_09.png',
    spBannerSrc: '/SP/Pair/Banner/s21_PairIndex_Banner_09.png',
    spKirinukiSrc: '/SP/Pair_Detail/Kirinuki/s32_Entry_Kirinuki_09.png',
    spNameSrc: '/SP/Pair_Detail/Name/s32_Pair_name_09.png',
    spBaseASrc: '/SP/Pair_Detail/HNBase/s32_Pair_HNBase_09_A.png',
    spBaseBSrc: '/SP/Pair_Detail/HNBase/s32_Pair_HNBase_09_B.png',
    description: '素材にかけるアイデアも見識も深い作者が\n遊びつくす動画に、視聴者も体感必至！',
    isPublished: true
  },
  {
    index: 10,
    name: 'FLAME KEEPER',
    frameSrc: '/Pair/Frame/31_Pair_Frame_10.png',
    hnASrc: '/Pair_Modal/HN/32_Pair_Modal_HN_10A.png',
    hnBSrc: '/Pair_Modal/HN/32_Pair_Modal_HN_10B.png',
    illustSrc: '/Pair_Modal/Illust/32_Pair_Modal_Illust_10.png',
    nameSrc: '/Pair_Modal/Name/32_Pair_Modal_Name_10.png',
    spIconSrc: '/SP/Pair_Detail/Icon/s32_PairIcon_10.png',
    spBannerSrc: '/SP/Pair/Banner/s21_PairIndex_Banner_10.png',
    spKirinukiSrc: '/SP/Pair_Detail/Kirinuki/s32_Entry_Kirinuki_10.png',
    spNameSrc: '/SP/Pair_Detail/Name/s32_Pair_name_10.png',
    spBaseASrc: '/SP/Pair_Detail/HNBase/s32_Pair_HNBase_10_A.png',
    spBaseBSrc: '/SP/Pair_Detail/HNBase/s32_Pair_HNBase_10_B.png',
    description: '視聴者を魅了し続けてきた二人が織りなす\n渾身の一作に懸ける熱、全身で浴びよ！',
    isPublished: true
  },
  {
    index: 11,
    name: '放課後おたずねものプロデューサーズ',
    frameSrc: '/Pair/Frame/31_Pair_Frame_11.png',
    hnASrc: '/Pair_Modal/HN/32_Pair_Modal_HN_11A.png',
    hnBSrc: '/Pair_Modal/HN/32_Pair_Modal_HN_11B.png',
    illustSrc: '/Pair_Modal/Illust/32_Pair_Modal_Illust_11.png',
    nameSrc: '/Pair_Modal/Name/32_Pair_Modal_Name_11.png',
    spIconSrc: '/SP/Pair_Detail/Icon/s32_PairIcon_11.png',
    spBannerSrc: '/SP/Pair/Banner/s21_PairIndex_Banner_11.png',
    spKirinukiSrc: '/SP/Pair_Detail/Kirinuki/s32_Entry_Kirinuki_11.png',
    spNameSrc: '/SP/Pair_Detail/Name/s32_Pair_name_11.png',
    spBaseASrc: '/SP/Pair_Detail/HNBase/s32_Pair_HNBase_11_A.png',
    spBaseBSrc: '/SP/Pair_Detail/HNBase/s32_Pair_HNBase_11_B.png',
    description: '流行の先陣を切ってきたヒットメーカー\n音MDM天の視聴者全員、狙い撃ちにする！',
    isPublished: true
  },
  {
    index: 12,
    name: '異常震域',
    frameSrc: '/Pair/Frame/31_Pair_Frame_12.png',
    hnASrc: '/Pair_Modal/HN/32_Pair_Modal_HN_12A.png',
    hnBSrc: '/Pair_Modal/HN/32_Pair_Modal_HN_12B.png',
    illustSrc: '/Pair_Modal/Illust/32_Pair_Modal_Illust_12.png',
    nameSrc: '/Pair_Modal/Name/32_Pair_Modal_Name_12.png',
    spIconSrc: '/SP/Pair_Detail/Icon/s32_PairIcon_12.png',
    spBannerSrc: '/SP/Pair/Banner/s21_PairIndex_Banner_12.png',
    spKirinukiSrc: '/SP/Pair_Detail/Kirinuki/s32_Entry_Kirinuki_12.png',
    spNameSrc: '/SP/Pair_Detail/Name/s32_Pair_name_12.png',
    spBaseASrc: '/SP/Pair_Detail/HNBase/s32_Pair_HNBase_12_A.png',
    spBaseBSrc: '/SP/Pair_Detail/HNBase/s32_Pair_HNBase_12_B.png',
    description: 'この二人の力がどこで奮うか予測不能！\n乱れ打つ作為からはもう逃れられない！？',
    isPublished: true
  },
  {
    index: 13,
    name: '',
    frameSrc: '/Pair/Frame/31_Pair_Frame_Secret_13.png',
    hnASrc: '',
    hnBSrc: '',
    illustSrc: '',
    nameSrc: '',
    spIconSrc: '/SP/Pair_Detail/Icon/s32_PairIcon_secret_13.png',
    spBannerSrc: '/SP/Pair/Banner/s21_PairIndex_Banner_Secret_13.png',
    spKirinukiSrc: '',
    spNameSrc: '',
    spBaseASrc: '',
    spBaseBSrc: '',
    description: '',
    isPublished: false
  },
  {
    index: 14,
    name: '',
    frameSrc: '/Pair/Frame/31_Pair_Frame_Secret_14.png',
    hnASrc: '',
    hnBSrc: '',
    illustSrc: '',
    nameSrc: '',
    spIconSrc: '/SP/Pair_Detail/Icon/s32_PairIcon_secret_14.png',
    spBannerSrc: '/SP/Pair/Banner/s21_PairIndex_Banner_Secret_14.png',
    spKirinukiSrc: '',
    spNameSrc: '',
    spBaseASrc: '',
    spBaseBSrc: '',
    description: '',
    isPublished: false
  },
  {
    index: 15,
    name: '',
    frameSrc: '/Pair/Frame/31_Pair_Frame_Secret_15.png',
    hnASrc: '',
    hnBSrc: '',
    illustSrc: '',
    nameSrc: '',
    spIconSrc: '/SP/Pair_Detail/Icon/s32_PairIcon_secret_15.png',
    spBannerSrc: '/SP/Pair/Banner/s21_PairIndex_Banner_Secret_15.png',
    spKirinukiSrc: '',
    spNameSrc: '',
    spBaseASrc: '',
    spBaseBSrc: '',
    description: '',
    isPublished: false
  },
  {
    index: 16,
    name: '',
    frameSrc: '/Pair/Frame/31_Pair_Frame_Secret_16.png',
    hnASrc: '',
    hnBSrc: '',
    illustSrc: '',
    nameSrc: '',
    spIconSrc: '/SP/Pair_Detail/Icon/s32_PairIcon_secret_16.png',
    spBannerSrc: '/SP/Pair/Banner/s21_PairIndex_Banner_Secret_16.png',
    spKirinukiSrc: '',
    spNameSrc: '',
    spBaseASrc: '',
    spBaseBSrc: '',
    description: '',
    isPublished: false
  },
  {
    index: 17,
    name: '',
    frameSrc: '/Pair/Frame/31_Pair_Frame_Secret_17.png',
    hnASrc: '',
    hnBSrc: '',
    illustSrc: '',
    nameSrc: '',
    spIconSrc: '/SP/Pair_Detail/Icon/s32_PairIcon_secret_17.png',
    spBannerSrc: '/SP/Pair/Banner/s21_PairIndex_Banner_Secret_17.png',
    spKirinukiSrc: '',
    spNameSrc: '',
    spBaseASrc: '',
    spBaseBSrc: '',
    description: '',
    isPublished: false
  },
  {
    index: 18,
    name: '',
    frameSrc: '/Pair/Frame/31_Pair_Frame_Secret_18.png',
    hnASrc: '',
    hnBSrc: '',
    illustSrc: '',
    nameSrc: '',
    spIconSrc: '/SP/Pair_Detail/Icon/s32_PairIcon_secret_18.png',
    spBannerSrc: '/SP/Pair/Banner/s21_PairIndex_Banner_Secret_18.png',
    spKirinukiSrc: '',
    spNameSrc: '',
    spBaseASrc: '',
    spBaseBSrc: '',
    description: '',
    isPublished: false
  },
  {
    index: 19,
    name: '',
    frameSrc: '/Pair/Frame/31_Pair_Frame_Secret_19.png',
    hnASrc: '',
    hnBSrc: '',
    illustSrc: '',
    nameSrc: '',
    spIconSrc: '/SP/Pair_Detail/Icon/s32_PairIcon_secret_19.png',
    spBannerSrc: '/SP/Pair/Banner/s21_PairIndex_Banner_Secret_19.png',
    spKirinukiSrc: '',
    spNameSrc: '',
    spBaseASrc: '',
    spBaseBSrc: '',
    description: '',
    isPublished: false
  },
  {
    index: 20,
    name: '',
    frameSrc: '/Pair/Frame/31_Pair_Frame_Secret_20.png',
    hnASrc: '',
    hnBSrc: '',
    illustSrc: '',
    nameSrc: '',
    spIconSrc: '/SP/Pair_Detail/Icon/s32_PairIcon_secret_20.png',
    spBannerSrc: '/SP/Pair/Banner/s21_PairIndex_Banner_Secret_20.png',
    spKirinukiSrc: '',
    spNameSrc: '',
    spBaseASrc: '',
    spBaseBSrc: '',
    description: '',
    isPublished: false
  }
];

export default pairs;
